### ISSUE TITLE
"Texture 'Terrain (16x16) 1' is not readable"

### ISSUE THREAD

**Issue by samyoed** [leocub58/Tilemap-to-PNG-Unity#1]
When I try to run it, it spits out this error.
![image](https://user-images.githubusercontent.com/35967405/79931424-fdc74d00-8418-11ea-9350-1b44edec58ed.png)

**Comment by leocub58** [comment]
you need to put the texture in "readable"

![Screenshot_2](https://user-images.githubusercontent.com/48869211/79986523-13ce1f80-84a4-11ea-8f17-9ef5397ca909.png)
